baseURL = "https://maciekpiasecki.github.io/my-website/"
languageCode = "en-us"
title = "Maciek Piasecki"
theme = "archie"
relativeURLs = true

[params]
	mode="dark"
	useCDN=false

[caches]
  [caches.images]
    dir = ':cacheDir/images'