baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Maciek Piasecki'

[module]
[[module.imports]]
path = "github.com/tomfran/typo"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false


homeIntroTitle = 'Hello. I am a digital security personal trainer and advisor for high-risk projects. Please feel encouraged to write me.'

homeIntroContent = """
**I will be happy to give you a free risk assessment based on [threat modelling](https://owasp.org/www-community/Threat_Modeling) principles.**

My e-mail address is [info at maciekpiasecki dot com] and you can download my [public PGP key here](/pgp/info-at-maciekpiasecki-publickey.asc).

**Both commercial and non-commercial projects are welcome.**

# My background

For over a decade I worked as a reporter in high-risk environments, providing coverage of protest movements, law enforcement tactics, and digital technology. To do this, I need to be in contact with communities vulnerable to organised violence, public institutions as well as political extremist groups. Trust and confidentiality were vital in these endeavours.

Now I use this experience to make you and your team more secure.

# Services

Whether you are a business leader, media, film, legal or arts professional, human rights activist or someone with a large social media presence - I will be happy to speak with you and find tailored solutions for you. These can include trainings for your team, complex operational plans or security audits.

I work closely with a legal and technical team to ensure an in-depth approach. My absolute priority is good communication. I will make sure to explain complex issues on the level appropriate to your technical knowledge.

# Standards

As a member of ISACA and ISC2 cybersecurity professional organisations, I adhere to the highest ethical standards, including confidentiality.

I have also taken part in accessibility and cultural awareness trainings provided by UNHCR affiliates and ICANN. Having a disability myself, I take all your needs in this matter very seriously.

# Past projects, references and citations

I have spoken at multiple security and human rights conferences about the needs of high-risk end users and ways to reach them, including tabletop exercises (TTX) and virtual reality (VR) simulations. The events included Warsaw Hack Summit, Tiblisi Datafest, RightsCon 12, and POINT in Sarajevo. 

I'm an alumnus of the [DFRLab's Digital Sherlocks OSINT programme](https://dfrlab.org/digital-sherlocks/) and [Internews Journalist Security Fellowship](https://internews.org/areas-of-expertise/global-tech/global-tech-projects/internews-journalist-security-fellowship-in-central-and-southeastern-europe/). At ISACA I sit in the EU Advocacy Task Force, which [consults EU institutions](https://www.isaca.org/-/media/files/isacadp/project/isaca/about-us/isaca-vision-paper-empowering-europes-digital-future-with-cyber-resilience.pdf) to provide better cyber resilience to all European citizens.

My work has been cited and/or consulted by the European Parliament working groups, [Council of Europe](https://www.ecpmf.eu/wp-content/uploads/2024/03/Annual-Report-2024-CoE-Platform-Journalists-.pdf),
[OHCHR](https://uprdoc.ohchr.org/uprweb/downloadfile.aspx?filename=10157&file=EnglishTranslation),
[OSCE](https://www.osce.org/files/f/documents/2/f/467892.pdf), and [National Endowment for Democracy](https://www.demdigest.org/reasons-for-hope-illiberal-wave-vs-democratic-resilience), among others. I have also taken part in policy drafting regarding satellite connectivity for the UN.

I will be happy to share my past projects and client referrals with you once we get in touch, but due to their often sensitive nature, I refrain to publish them here. Thank you for your understanding.

# I'm looking forward to your questions and ideas for possible collaborations.

While security is often an intimidating and esoteric subject, I'll make sure to take some of that stress off your shoulders.

"""